sudo: required

notifications:
  email: false

language: rust

before_install:
  - sudo apt-get install -y upx-ucl
  - sudo apt-get install -y rubygems
  - sudo gem install os
  - ruby --version
  - rake --version

script:
  - rake upx
  - rake test
